<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7HaZD8F\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7HaZD8F/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container7HaZD8F.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\Container7HaZD8F\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \Container7HaZD8F\srcDevDebugProjectContainer(array(
    'container.build_hash' => '7HaZD8F',
    'container.build_id' => '581e9cbf',
    'container.build_time' => 1529869581,
), __DIR__.\DIRECTORY_SEPARATOR.'Container7HaZD8F');
